name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macOS-11
    strategy:
      matrix:
        xcode:
          - 12.4
          - 12.5.1

    steps:
    - uses: actions/checkout@master
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - uses: actions/cache@v1
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Cartfile.resolved') }}
    - name: Carthage
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: carthage bootstrap --use-xcframeworks --no-use-binaries --platform iOS --cache-builds
    - name: Run unit tests with iPhone 11
      run:  xcodebuild clean test -project RandomUser.xcodeproj -scheme RandomUser -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty && exit ${PIPESTATUS[0]}
