name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Carthage
      run: |
       carthage checkout
       carthage build --platform ios
    - name: Run unit tests with iPhone 8
      run:  xcodebuild clean test -project RandomUser.xcodeproj -scheme RandomUser -destination "platform=iOS Simulator,name=iPhone 8" | xcpretty && exit ${PIPESTATUS[0]}
