name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@v1
      id: carthage-cache
      with:
        path: Carthage
        key: ${{ runner.os }}-xcode-11-5-${{ hashFiles('**/Cartfile.resolved') }}
    - name: Carthage
      if: steps.carthage-cache.outputs.cache-hit != 'true'
      run: carthage bootstrap --no-use-binaries --platform iOS --cache-builds
    - name: Run unit tests with iPhone 11
      run:  xcodebuild clean test -project RandomUser.xcodeproj -scheme RandomUser -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty && exit ${PIPESTATUS[0]}
